### ISSUE TITLE
Issue installing from brew

### ISSUE THREAD

**Issue by teajaymars** [render-oss/homebrew-render#12]
```bash
~/code ⌚ 17:50:04
$ brew tap render-oss/render


~/code ⌚ 17:50:09
$ brew install render

==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################################################################ 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################################################################################ 100.0%
==> Fetching render-oss/render/render
==> Cloning https://github.com/render-oss/render-cli.git
Updating /Users/zephod/Library/Caches/Homebrew/render--git
==> Checking out tag v0.1.8
HEAD is now at 7ae178b Merge pull request #61 from render-oss/robdimarco/update-dependencies-lock-file
HEAD is now at 7ae178b Merge pull request #61 from render-oss/robdimarco/update-dependencies-lock-file
==> Installing render from render-oss/render
==> make build-completions
Last 15 lines from /Users/zephod/Library/Logs/Homebrew/render/01.make:
                --allow-net \
                --allow-read \
                --allow-run \
                --allow-write \
                --allow-env \
                --target=aarch64-apple-darwin \
                --output=./bin/render \
                ./entry-point.ts
Check file:///private/tmp/render-20231013-79670-1trne6m/entry-point.ts
error: TS2339 [ERROR]: Property 'connection' does not exist on type 'WebSocketStream'.
          conn = await stream.connection;
                              ~~~~~~~~~~
    at file:///private/tmp/render-20231013-79670-1trne6m/commands/services/tail.ts:62:31
make[1]: *** [build-macos-aarch64] Error 1
make: *** [build-local] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/render-oss/homebrew-render/issues
```

I've just reinstalled homebrew using the Mac package installer (on M1 Max, Mac OS Sonoma 14.0), and am trying to set up my favourite CLI utilities.

Deno appears to be installed OK:

```bash
~/code ⌚ 17:52:49
$ which deno
/opt/homebrew/bin/deno

~/code ⌚ 17:52:55
$ deno --version
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2
```

**Comment by cblavier** [comment]
same issue here, compiling from an Apple Silicon Mac

**Comment by simonc** [comment]
Hi. Same issue building on an M1 MacBook Pro with Sonoma.

**Comment by dvirben** [comment]
Hi, same problem
Using macbook pro m1 Sonoma 14
error: TS2339 [ERROR]: Property 'connection' does not exist on type 'WebSocketStream'.
          conn = await stream.connection;
                              ~~~~~~~~~~
    at file:///private/tmp/render-20231029-85179-2cjcw4/commands/services/tail.ts:62:31
make[1]: *** [build-macos-aarch64] Error 1
make: *** [build-local] Error 2

**Comment by digerata** [comment]
Same. Macbook Pro M1 Sonoma 14.1.

```
==> make build-completions
Last 15 lines from /Users/mikewille/Library/Logs/Homebrew/render/01.make:
		--allow-net \
		--allow-read \
		--allow-run \
		--allow-write \
		--allow-env \
		--target=aarch64-apple-darwin \
		--output=./bin/render \
		./entry-point.ts
Check file:///private/tmp/render-20231101-24149-1ppe45m/entry-point.ts
error: TS2339 [ERROR]: Property 'connection' does not exist on type 'WebSocketStream'.
          conn = await stream.connection;
                              ~~~~~~~~~~
    at file:///private/tmp/render-20231101-24149-1ppe45m/commands/services/tail.ts:62:31
make[1]: *** [build-macos-aarch64] Error 1
make: *** [build-local] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/render-oss/homebrew-render/issues
```

**Comment by Tadwork** [comment]
It seems like the WebSocketStream api changed (https://deno.land/api@v1.38.0?s=WebSocketStream&unstable=) and instead of a `connection` property the WebSocketConnection can be found at `socket.opened`. This seems to have been changed in this commit to Deno https://github.com/denoland/deno/pull/20878. The `WebSocketConnection` API is marked as unstable so this may continue to change and break

**Comment by dvirben** [comment]
I am executing the command:
`brew install render`
How can i configure it and use your suggestion?


> It seems like the WebSocketStream api changed (https://deno.land/api@v1.38.0?s=WebSocketStream&unstable=) and instead of a `connection` property the WebSocketConnection can be found at `socket.opened`. This seems to have been changed in this commit to Deno [denoland/deno#20878](https://github.com/denoland/deno/pull/20878). The `WebSocketConnection` API is marked as unstable so this may continue to change and break

**Comment by kshnyakin** [comment]
> It seems like the WebSocketStream api changed (https://deno.land/api@v1.38.0?s=WebSocketStream&unstable=) and instead of a `connection` property the WebSocketConnection can be found at `socket.opened`. This seems to have been changed in this commit to Deno [denoland/deno#20878](https://github.com/denoland/deno/pull/20878). The `WebSocketConnection` API is marked as unstable so this may continue to change and break

For me worked next changes in `commands/services/tail.ts`

```
        try {
          conn = await stream.opened;
          reader = await conn.readable.getReader();
          writer = await conn.writable.getWriter();
        } catch (err) {
          throw err;
        }
```
