### ISSUE TITLE
Getting type errors on install

### ISSUE THREAD

**Issue by techguysimon** [render-oss/homebrew-render#4]
I'm trying to install the render cli on my m1 mac and I'm getting the error below.
macOS: Ventura 13.0
```
==> Checking out tag v0.1.5
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
==> Installing render from render-oss/render
==> make build-completions
Last 15 lines from /Users/simon/Library/Logs/Homebrew/render/01.make:
    at file:///private/tmp/render-20230301-31936-1arp6j9/config/index.ts:121:8

TS2322 [ERROR]: Type 'string' is not assignable to type '"singapore" | "oregon" | "ohio" | "frankfurt"'.
  return s;
  ~~~~~~~~~
    at file:///private/tmp/render-20230301-31936-1arp6j9/config/index.ts:125:3

TS2347 [ERROR]: Untyped function calls may not accept type arguments.
        const logEntryValidator = ajv.compile<LogTailEntry>(LogTailEntry);
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///private/tmp/render-20230301-31936-1arp6j9/commands/services/tail.ts:69:35

Found 8 errors.
make[1]: *** [build-macos-aarch64] Error 1
make: *** [build-local] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/render-oss/homebrew-render/issues
  ```

**Comment by egonzalez1958** [comment]
What can i do to use render cli if this installion has failed?

error: error sending request for url (https://raw.githubusercontent.com/lodash/lodash/4.17.21-es/_createMathOperation.js): error trying to connect: tls handshake eof
    at https://raw.githubusercontent.com/lodash/lodash/4.17.21-es/add.js:1:33
make[1]: *** [Makefile:10: deps] Error 1
make[1]: Leaving directory '/tmp/render-20230413-967298-2dyk22'
make: *** [Makefile:4: build-local] Error 2

**Comment by robdimarco-render** [comment]
Fix has been applied. You should be able to run 

```
brew tap render-oss/render
brew install render
```

and have it succeed now.

**Comment by egonzalez1958** [comment]
Thanks, but...

Where should I do that?

Regards!
*Eduardo González C.*
***@***.*** ***@***.***>*
